### PR TITLE
[WIP] rffit: Improve interactive help

### PR DESCRIPTION
**Pull request by kerel-fs**
Changes to rffit interactive help:
- Group & Re-order entries
- Fix associated character for "Save selected points into file" / `S`
- Add command description for "Select all points in present window" / `s`
- Improve command description for reload deleted points / `u`
- Unify language on selection / highlighting:
  Upon loading, all points are "un-selected". The user can "select" points
  via commands (previously called "highlighting"), but also "de-select" points
  again. Additionally points can be "deleted" (i.e. made invisble and ignored
  by the fitting methods) and "reloaded".

The action to  "delete points" was called "unselect points" previously which could be confused with "de-highlighting" points. The new recommended scheme tries to avoid this.

### CODE REVIEW

**Comment by kerel-fs** [comment]
I'll rebase this patch.

**Comment by cbassa** [comment]
Oops... I saw your comment too late. I think I resolved all conflicts, but am double checking now. Thanks for the PR!

**Comment by kerel-fs** [comment]
Rebase done and force-pushed. Ah, too late :D

**Comment by kerel-fs** [comment]
Looks almost good.
"Invert selection" was re-assigned on `T` (previously `I`), and a minor rewording got mangled. Should I create a fixup PR?

**Comment by cbassa** [comment]
Thanks for the warning, I missed that but it is fixed now!

**Pull request merged**
